const dictionary = {
abandon:"to leave something completely",
ability:"the power or skill to do something",
able:"having the power to do something",
aboard:"on or inside a vehicle",
about:"concerning or related to",
above:"at a higher level",
absent:"not present",
absolute:"complete and total",
absorb:"to take in something",
abstract:"existing in thought but not physical",
abundant:"more than enough",
abuse:"to treat someone badly",
academy:"a place of study or training",
accelerate:"to increase speed",
accept:"to agree to receive",
access:"the ability to enter or use",
accident:"an unexpected harmful event",
accompany:"to go with someone",
accomplish:"to successfully complete",
account:"a report or description",
accurate:"correct and exact",
accuse:"to say someone did wrong",
achieve:"to reach a goal",
acid:"a chemical substance with sour taste",
acknowledge:"to accept something as true",
acquire:"to obtain something",
across:"from one side to another",
act:"to do something",
action:"the process of doing",
active:"full of energy",
activity:"something a person does",
actor:"a person who performs in movies",
actual:"real or true",
adapt:"to adjust to new conditions",
add:"to put something together",
addition:"the act of adding",
address:"details of a location",
adequate:"enough for a need",
adjust:"to change slightly",
administration:"management of an organization",
admire:"to respect or like greatly",
admit:"to accept something as true",
adopt:"to take and raise as one's own",
adult:"a fully grown person",
advance:"to move forward",
advantage:"something helpful",
adventure:"an exciting experience",
advertise:"to promote something publicly",
advice:"guidance about decisions",
advise:"to give suggestions",
affair:"an event or situation",
affect:"to influence something",
afford:"to have enough money",
afraid:"feeling fear",
after:"later than something",
afternoon:"time between noon and evening",
again:"one more time",
against:"in opposition to",
age:"length of time someone lived",
agency:"an organization providing service",
agenda:"a list of plans",
agent:"a person acting for another",
aggressive:"ready to attack",
agree:"to have the same opinion",
agreement:"a shared decision",
ahead:"in front of something",
aid:"help or support",
aim:"a goal or purpose",
air:"the invisible gas we breathe",
aircraft:"a vehicle that flies",
airport:"a place where airplanes land",
alarm:"a warning signal",
album:"a collection of recordings",
alert:"quick to notice danger",
alien:"a person from another country",
alive:"living not dead",
all:"the whole amount",
allow:"to permit something",
almost:"not quite",
alone:"without other people",
along:"moving in a line",
already:"before the present time",
also:"in addition",
alter:"to change something",
alternative:"another option",
although:"in spite of the fact",
always:"at all times",
amazing:"very surprising",
ambition:"a strong desire to achieve",
among:"in the middle of many",
amount:"a quantity of something",
analysis:"detailed examination",
ancient:"very old",
anger:"strong feeling of displeasure",
angle:"space between two lines",
animal:"a living creature",
announce:"to tell publicly",
annual:"happening every year",
answer:"a response to a question",
anxiety:"feeling of worry",
any:"one or more",
anybody:"any person",
anywhere:"in any place",
apart:"separated by distance",
apparent:"clearly seen",
appeal:"a request for help",
appear:"to come into sight",
apple:"a round fruit",
application:"a formal request",
apply:"to use something",
appoint:"to assign a position",
approach:"to move closer",
approve:"to agree with",
area:"a region of space",
argue:"to disagree strongly",
arise:"to begin to exist",
arm:"upper limb of the body",
army:"a country's military force",
around:"on every side",
arrange:"to organize",
arrest:"to take into custody",
arrive:"to reach a place",
arrow:"a pointed weapon",
art:"creative expression",
article:"a written piece",
artist:"a person who creates art",
artificial:"made by humans",
ask:"to request information",
aspect:"a particular part",
assess:"to evaluate something",
asset:"something valuable",
assign:"to give a task",
assist:"to help",
assume:"to believe without proof",
assure:"to promise confidently",
astonish:"to surprise greatly",
atmosphere:"layer of gases around earth",
attach:"to fasten together",
attack:"to act violently against",
attempt:"to try",
attend:"to be present",
attention:"focus of the mind",
attitude:"a way of thinking",
attract:"to draw interest",
audience:"people watching an event",
author:"a person who writes",
authority:"power to give orders",
available:"ready to use",
average:"the typical value",
avoid:"to stay away from",
awake:"not sleeping",
award:"a prize for achievement",
aware:"having knowledge",
away:"at a distance",
awesome:"extremely impressive",
baby:"a very young child",
back:"the rear part of something",
background:"the setting or situation behind something",
backpack:"a bag carried on the back",
backup:"support or extra help",
bacteria:"very small living organisms",
bad:"not good",
badge:"a small sign worn to show identity",
bag:"a container made of cloth or plastic",
bake:"to cook using dry heat",
balance:"a state of being steady and equal",
balcony:"a platform outside a building",
ball:"a round object used in games",
balloon:"a rubber bag filled with air or gas",
ban:"to officially forbid something",
banana:"a long curved yellow fruit",
band:"a group of musicians",
bank:"a place where money is kept",
bar:"a long piece of metal or wood",
bare:"without covering",
bargain:"something bought at a good price",
bark:"the outer covering of a tree",
barn:"a building for farm animals",
barrel:"a large round container",
base:"the bottom or foundation",
basic:"simple and important",
basis:"the main support of something",
basket:"a container made of woven material",
basketball:"a sport played with a ball and hoop",
bat:"an animal that flies at night",
batch:"a group of things made together",
bath:"washing the body in water",
battery:"a device that stores electrical energy",
battle:"a fight between groups",
beach:"a sandy area near the sea",
beam:"a long piece of wood or metal",
bean:"a small seed used as food",
bear:"a large wild animal",
beard:"hair growing on a man's chin",
beat:"to strike repeatedly",
beautiful:"very pleasing to look at",
beauty:"the quality of being attractive",
because:"for the reason that",
become:"to start being something",
bed:"a piece of furniture for sleeping",
bee:"a small insect that makes honey",
beef:"meat from a cow",
before:"earlier than something",
begin:"to start something",
beginning:"the start of something",
behavior:"the way someone acts",
behind:"at the back of something",
belief:"a strong feeling something is true",
believe:"to think something is true",
bell:"a metal object that rings",
belong:"to be owned by someone",
below:"at a lower level",
belt:"a strip worn around the waist",
bench:"a long seat",
bend:"to make something curved",
benefit:"something that helps",
best:"better than all others",
bet:"to risk money on a result",
better:"more good or improved",
between:"in the middle of two things",
beyond:"farther than something",
bicycle:"a vehicle with two wheels",
bid:"an offer of price",
big:"large in size",
bill:"a statement of money owed",
bird:"an animal with wings and feathers",
birth:"the act of being born",
birthday:"the yearly celebration of birth",
biscuit:"a small baked bread product",
bit:"a small piece",
bite:"to cut with the teeth",
bitter:"having a sharp taste",
black:"the darkest color",
blade:"the sharp part of a knife",
blame:"to say someone is responsible",
blank:"empty or not filled",
blanket:"a cover used for warmth",
blast:"a strong explosion",
bleed:"to lose blood",
blend:"to mix together",
bless:"to ask for protection",
blind:"unable to see",
block:"a solid piece of material",
blood:"red liquid in the body",
bloom:"to produce flowers",
blow:"to move air",
blue:"the color of the sky",
board:"a flat piece of wood",
boat:"a vehicle that travels on water",
body:"the physical structure of a person",
boil:"to heat a liquid until bubbles form",
bold:"brave and confident",
bolt:"a metal fastener",
bomb:"a weapon that explodes",
bond:"a connection between people",
bone:"hard structure inside the body",
book:"a set of written pages",
boom:"a deep loud sound",
boost:"to increase something",
border:"the line separating areas",
boring:"not interesting",
borrow:"to take something to return later",
boss:"a person in charge",
both:"two together",
bother:"to annoy or trouble",
bottle:"a container for liquids",
bottom:"the lowest part",
cab:"a taxi vehicle",
cabin:"a small wooden house",
cable:"a thick wire used for electricity",
cafe:"a small restaurant that serves coffee",
cage:"a structure used to keep animals",
cake:"a sweet baked dessert",
calculate:"to find an answer using math",
calendar:"a chart showing days and months",
call:"to speak to someone by phone",
calm:"peaceful and quiet",
camera:"a device used to take photos",
camp:"a place where people stay in tents",
campaign:"a series of actions for a goal",
campus:"the grounds of a school or college",
can:"to be able to do something",
cancel:"to stop something from happening",
cancer:"a serious disease of body cells",
candidate:"a person applying for a position",
candle:"a stick of wax that gives light",
candy:"a sweet sugar food",
canvas:"a strong cloth used for painting",
cap:"a hat with a small shade",
capable:"having the ability to do something",
capacity:"the maximum amount something can hold",
capital:"the main city of a country",
captain:"the leader of a team or ship",
capture:"to catch something",
car:"a vehicle with four wheels",
carbon:"a chemical element found in nature",
card:"a small piece of thick paper",
care:"to look after something",
career:"a long-term job or profession",
careful:"showing attention to avoid mistakes",
cargo:"goods carried by a ship or plane",
carpet:"a thick floor covering",
carry:"to hold and move something",
cart:"a small vehicle for carrying goods",
case:"a situation or example",
cash:"money in the form of notes or coins",
castle:"a large strong building from the past",
casual:"relaxed and not formal",
cat:"a small animal kept as a pet",
catalog:"a list of items",
catch:"to grab something moving",
category:"a group of similar things",
cause:"the reason something happens",
caution:"care taken to avoid danger",
cave:"a large hole in the side of a hill",
cease:"to stop",
ceiling:"the inside top of a room",
celebrate:"to do something special for an event",
celebrity:"a famous person",
cell:"the smallest unit of life",
center:"the middle point",
central:"in the middle",
century:"a period of 100 years",
ceremony:"a formal event",
certain:"sure or definite",
chain:"connected rings of metal",
chair:"a seat for one person",
challenge:"a difficult task",
champion:"a winner of a competition",
chance:"a possibility",
change:"to make something different",
channel:"a passage for water or communication",
chapter:"a section of a book",
character:"a person in a story",
charge:"to ask money for something",
charity:"help given to people in need",
chart:"a visual display of information",
chase:"to run after something",
cheap:"low in price",
check:"to examine something",
cheer:"to shout in support",
cheese:"food made from milk",
chef:"a professional cook",
chemical:"a substance used in science",
chest:"the front part of the body",
chief:"the main leader",
child:"a young person",
choice:"the act of choosing",
choose:"to pick one option",
circle:"a round shape",
city:"a large town",
civil:"relating to citizens",
claim:"to say something is true",
class:"a group of students",
clean:"free from dirt",
clear:"easy to understand",
clerk:"a person who works in an office or shop",
clever:"quick to understand",
climate:"the usual weather of a place",
climb:"to go upward",
clock:"a device that shows time",
close:"near in distance",
cloth:"fabric used for clothing",
cloud:"a mass of water vapor in the sky",
club:"a group of people with a common interest",
coach:"a person who trains a team",
coal:"a black rock used for fuel",
coast:"land next to the sea",
coat:"an outer piece of clothing",
code:"a system of symbols or rules",
coffee:"a drink made from roasted beans",
coin:"a piece of metal used as money",
cold:"having a low temperature",
dance:"to move the body to music",
danger:"the possibility of harm",
dangerous:"likely to cause harm",
dare:"to have courage to do something",
dark:"having little or no light",
data:"facts or information used for analysis",
date:"a particular day of the month or year",
daughter:"a female child",
day:"a period of 24 hours",
dead:"not alive",
deal:"an agreement between people",
debate:"a discussion where people argue different ideas",
debt:"money that is owed to someone",
decade:"a period of ten years",
decay:"to slowly break down",
deceive:"to make someone believe something false",
decide:"to make a choice",
decision:"a choice made after thinking",
declare:"to announce something officially",
decline:"to become smaller or weaker",
decorate:"to make something look more attractive",
decrease:"to become less",
deep:"far down from the top",
deer:"a wild animal with long legs and antlers",
defeat:"to win against someone",
defend:"to protect from attack",
define:"to explain the meaning of something",
degree:"a unit of measurement or level",
delay:"to make something happen later",
deliver:"to bring something to someone",
demand:"to strongly ask for something",
demonstrate:"to show how something works",
dense:"closely packed together",
deny:"to say something is not true",
department:"a section of an organization",
depend:"to rely on someone or something",
deposit:"to place money in a bank",
depth:"the distance from top to bottom",
describe:"to explain what something is like",
desert:"a dry place with little rain",
deserve:"to be worthy of something",
design:"to plan how something will look",
desire:"a strong wish for something",
desk:"a table used for writing or working",
despair:"a feeling of hopelessness",
destroy:"to completely ruin something",
detail:"a small part of something",
detect:"to discover something hidden",
determine:"to decide or control something",
develop:"to grow or improve",
device:"a tool or machine",
devote:"to give time or effort to something",
dialogue:"a conversation between people",
diamond:"a hard precious stone",
diary:"a book for writing daily events",
dictionary:"a book of words and meanings",
die:"to stop living",
diet:"the food a person eats",
difference:"how things are not the same",
different:"not the same",
difficult:"hard to do",
dig:"to make a hole in the ground",
digital:"related to computer technology",
dignity:"a sense of respect and honor",
dilemma:"a difficult choice between options",
dimension:"a measure of size or space",
dinner:"the main meal of the day",
direct:"to guide or control something",
direction:"the path something moves",
director:"a person who manages something",
dirty:"not clean",
disagree:"to have a different opinion",
disappear:"to vanish from sight",
disaster:"a sudden event causing great damage",
discipline:"training to follow rules",
discover:"to find something new",
discuss:"to talk about something",
disease:"an illness affecting the body",
dish:"a container used for food",
dismiss:"to send someone away",
display:"to show something publicly",
distance:"space between two places",
distinct:"clearly different",
distinguish:"to recognize differences",
distribute:"to give out to many people",
district:"an area of a city or country",
disturb:"to interrupt peace",
divide:"to separate into parts",
divorce:"the legal ending of marriage",
doctor:"a person trained to treat illness",
document:"a written or printed record",
dog:"a common domestic animal",
domestic:"related to home or country",
dominant:"having power or control",
door:"a movable barrier used to open or close an entrance",
double:"twice the amount",
doubt:"a feeling of uncertainty",
down:"toward a lower place",
dozen:"a group of twelve",
draft:"a rough version of writing",
drag:"to pull something along the ground",
drama:"a story acted on stage or screen",
draw:"to create a picture with lines",
dream:"images or thoughts during sleep",
dress:"a piece of clothing worn by women",
drink:"to take liquid into the body",
drive:"to control a vehicle",
drop:"to fall downward",
eager:"very interested and excited",
eagle:"a large bird of prey",
early:"before the usual time",
earn:"to receive money for work",
earth:"the planet we live on",
ease:"freedom from difficulty",
east:"the direction where the sun rises",
easy:"not difficult",
eat:"to put food into the mouth and swallow",
echo:"a sound that repeats after bouncing",
edge:"the outer limit of something",
edit:"to make changes to improve writing",
educate:"to teach someone",
education:"the process of learning",
effect:"a result of something",
effective:"producing the desired result",
efficient:"working well without wasting time",
effort:"energy used to do something",
egg:"an oval object laid by birds",
eight:"the number after seven",
either:"one or the other of two",
elbow:"the joint in the middle of the arm",
elder:"a person older than others",
elect:"to choose by voting",
electric:"related to electricity",
electricity:"energy produced by electric charge",
element:"a basic part of something",
elephant:"a very large animal with a trunk",
elevator:"a machine that moves people between floors",
else:"in addition or different",
email:"a message sent electronically",
embarrass:"to make someone feel shy or ashamed",
embrace:"to hold someone closely",
emerge:"to come out into view",
emotion:"a strong feeling",
emphasize:"to give special importance",
empire:"a group of countries ruled by one leader",
employ:"to give someone a job",
employee:"a person who works for someone",
employer:"a person or company that hires workers",
empty:"containing nothing",
enable:"to make something possible",
encounter:"to meet unexpectedly",
encourage:"to give support or confidence",
end:"the final part of something",
enemy:"a person who is against you",
energy:"power used to do work",
engage:"to take part in something",
engine:"a machine that produces power",
engineer:"a person who designs machines",
enjoy:"to take pleasure in something",
enough:"as much as needed",
ensure:"to make certain something happens",
enter:"to go inside",
entire:"whole or complete",
entrance:"a place to enter",
envelope:"a paper cover for a letter",
environment:"the natural world around us",
equal:"the same in amount or value",
equipment:"tools needed for a task",
error:"a mistake",
escape:"to get free from danger",
especially:"more than usual",
essay:"a short piece of writing",
essential:"very important",
establish:"to start something firmly",
estate:"land and property owned by someone",
estimate:"to guess a value or amount",
even:"flat or equal",
evening:"time between afternoon and night",
event:"something that happens",
eventually:"in the end",
ever:"at any time",
every:"each one of a group",
evidence:"facts showing something is true",
evil:"morally bad",
exact:"precise and correct",
examine:"to inspect carefully",
example:"something used to explain",
exceed:"to go beyond a limit",
excellent:"extremely good",
except:"not including",
exchange:"to give something and receive another",
excite:"to cause strong interest",
excuse:"a reason for a mistake",
execute:"to carry out a plan",
exercise:"activity for physical fitness",
exhibit:"to show publicly",
exist:"to be real",
expand:"to become larger",
expect:"to believe something will happen",
expense:"money spent",
experience:"knowledge gained from doing",
experiment:"a scientific test",
expert:"a person with great knowledge",
explain:"to make something clear",
explode:"to burst violently",
explore:"to travel to learn about a place",
export:"to send goods to another country",
expose:"to reveal something",
express:"to show thoughts or feelings",
extend:"to make longer",
extra:"more than needed",
eye:"the organ used for seeing",
face:"the front part of the head",
fact:"something that is true",
factor:"something that influences a result",
factory:"a building where goods are made",
fade:"to lose color or brightness",
fail:"to not succeed",
failure:"lack of success",
faint:"weak or not clear",
fair:"just and reasonable",
faith:"strong belief or trust",
fall:"to drop down",
false:"not true",
fame:"being widely known",
familiar:"well known",
family:"people related by blood",
famous:"known by many people",
fan:"a device that moves air",
fancy:"decorative or special",
fantasy:"imagination of unreal things",
far:"a long distance away",
farm:"land used for growing crops",
farmer:"a person who works on a farm",
fashion:"popular style of clothing",
fast:"moving quickly",
fat:"having a lot of body weight",
fate:"events believed to happen in the future",
father:"a male parent",
fault:"a mistake or defect",
favor:"an act of kindness",
favorite:"liked more than others",
fear:"feeling of being afraid",
feast:"a large special meal",
feather:"light covering of a bird",
feature:"an important part",
federal:"related to a central government",
fee:"money paid for a service",
feed:"to give food",
feel:"to experience emotion or touch",
feeling:"an emotion or sensation",
female:"relating to a woman or girl",
fence:"a barrier around land",
festival:"a special celebration",
fetch:"to go and bring something",
fever:"a high body temperature",
few:"a small number",
fiber:"thin thread-like material",
fiction:"a story that is not real",
field:"an open area of land",
fierce:"very strong or aggressive",
fight:"to use force against someone",
figure:"a number or shape",
file:"a collection of documents",
fill:"to make something full",
film:"a movie or thin layer",
final:"last in order",
finance:"management of money",
find:"to discover something",
fine:"very good or acceptable",
finger:"one of the five parts of the hand",
finish:"to complete something",
fire:"heat and light from burning",
firm:"strong and solid",
first:"coming before all others",
fish:"an animal that lives in water",
fit:"healthy and in good shape",
fix:"to repair something",
flag:"a cloth symbol of a country",
flame:"the bright part of fire",
flash:"a quick burst of light",
flat:"level and smooth",
flavor:"the taste of food",
flee:"to run away from danger",
flexible:"able to bend easily",
flight:"a journey through the air",
float:"to stay on the surface of water",
flood:"overflow of water onto land",
floor:"the bottom surface of a room",
flower:"the colorful part of a plant",
flow:"to move smoothly like water",
fly:"to move through the air",
focus:"to concentrate attention",
fold:"to bend something over itself",
follow:"to go after someone",
food:"things eaten for energy",
fool:"a person who acts unwisely",
foot:"the lower part of the leg",
force:"power used to move something",
forest:"a large area of trees",
forget:"to not remember",
forgive:"to stop feeling angry",
fork:"a tool used to eat food",
form:"the shape of something",
formal:"following rules or traditions",
former:"previous or earlier",
fortune:"great wealth or luck",
forward:"toward the front",
found:"to start something new",
fragile:"easily broken",
frame:"a structure that supports something",
free:"not controlled or limited",
freeze:"to turn into ice",
fresh:"new or recently made",
friend:"a person you like and trust",
front:"the forward part",
fruit:"a sweet product of a plant",
fuel:"a substance used to produce energy",
full:"containing as much as possible",
fun:"something enjoyable",
function:"the purpose of something",
fund:"money saved for a purpose",
future:"the time that is yet to come",
gain:"to get or obtain something",
galaxy:"a huge system of stars in space",
gallery:"a place where art is displayed",
game:"an activity played for fun",
gap:"an empty space between things",
garage:"a building for keeping vehicles",
garden:"a place where plants are grown",
gas:"a substance like air",
gate:"a movable barrier in a fence",
gather:"to collect things together",
gear:"equipment or tools used for something",
gender:"classification as male or female",
gene:"a unit of heredity in living things",
general:"relating to most people or things",
generate:"to produce or create",
generation:"people born around the same time",
generous:"willing to give or share",
genius:"a person with great intelligence",
gentle:"kind and soft",
genuine:"real and true",
geography:"study of the earth and places",
gesture:"a movement of the body to express something",
ghost:"spirit of a dead person",
giant:"very large person or thing",
gift:"something given without payment",
girl:"a female child",
give:"to transfer something to someone",
glad:"feeling happy",
glass:"a hard clear material",
global:"relating to the whole world",
glory:"great honor or praise",
glove:"a covering for the hand",
glow:"to shine with light",
goal:"something you try to achieve",
goat:"an animal with horns and beard",
gold:"a valuable yellow metal",
good:"having positive qualities",
goods:"items that can be sold",
govern:"to control or rule",
government:"the system that rules a country",
grab:"to take quickly",
grace:"simple beauty or elegance",
grade:"a level or score",
grain:"a small hard seed",
grand:"large and impressive",
grant:"to give permission",
grape:"a small sweet fruit",
graph:"a visual chart of data",
grass:"green plants that cover the ground",
grateful:"feeling thankful",
grave:"a place where a dead person is buried",
great:"very good or important",
green:"the color of plants",
greet:"to welcome someone",
grief:"deep sadness",
grind:"to crush into small pieces",
grip:"to hold tightly",
ground:"the surface of the earth",
group:"several people or things together",
grow:"to increase in size",
growth:"the process of growing",
guard:"to protect someone or something",
guess:"to give an answer without certainty",
guest:"a person invited somewhere",
guide:"a person who shows the way",
guilt:"feeling responsible for wrongdoing",
guitar:"a musical instrument with strings",
gun:"a weapon that shoots bullets",
gym:"a place for exercise",
habit:"something done regularly",
hair:"thin strands growing on the head",
half:"one of two equal parts",
hall:"a large room or passage",
hand:"the part of the arm used to hold things",
handle:"a part used to hold something",
hang:"to attach something above the ground",
happen:"to take place",
happy:"feeling joy",
harbor:"a place where ships stop",
hard:"not soft or difficult",
harm:"damage or injury",
harvest:"to collect crops",
hat:"a covering for the head",
hate:"strong dislike",
have:"to own or possess",
head:"the top part of the body",
health:"the state of being well",
hear:"to notice sound",
heart:"organ that pumps blood",
heat:"high temperature",
heavy:"having great weight",
help:"to assist someone",
hero:"a brave person",
high:"tall or above average level",
hill:"a small raised area of land",
history:"study of past events",
hold:"to keep something in the hand",
hole:"an empty space in something",
holiday:"a special day for celebration",
home:"the place where someone lives",
hope:"a feeling of expectation",
horse:"a large animal used for riding",
hospital:"a place where sick people are treated",
host:"a person who receives guests",
hot:"having high temperature",
hour:"a period of sixty minutes",
house:"a building for living in",
human:"a person",
humor:"the quality of being funny",
habit:"something done regularly",
hair:"thin strands growing on the head",
half:"one of two equal parts",
hall:"a large room or passage",
hand:"the part of the arm used to hold things",
handle:"a part used to hold something",
hang:"to attach something above the ground",
happen:"to take place",
happy:"feeling joy or pleasure",
harbor:"a place where ships stop safely",
hard:"not soft or difficult to do",
harm:"damage or injury",
harvest:"to gather crops from fields",
hat:"a covering worn on the head",
hate:"a strong feeling of dislike",
have:"to own or possess something",
head:"the top part of the body",
health:"the state of being well",
healthy:"having good health",
hear:"to notice sound with ears",
heart:"the organ that pumps blood",
heat:"high temperature",
heavy:"having great weight",
height:"how tall something is",
help:"to assist someone",
helpful:"giving useful assistance",
hero:"a brave person admired by others",
hide:"to keep something out of sight",
high:"tall or above normal level",
hill:"a raised area of land",
hint:"a small clue or suggestion",
history:"study of past events",
hit:"to strike something",
hold:"to keep something in the hand",
hole:"an empty space in something",
holiday:"a special day for celebration",
home:"the place where someone lives",
honest:"telling the truth",
honor:"respect given to someone",
hope:"a feeling that something good will happen",
horizon:"the line where earth and sky meet",
horn:"a hard pointed part on animals",
horror:"a strong feeling of fear",
horse:"a large animal used for riding",
hospital:"a place where sick people are treated",
host:"a person who receives guests",
hot:"having a high temperature",
hotel:"a place where travelers stay",
hour:"a period of sixty minutes",
house:"a building for living in",
human:"a person",
humble:"not proud or arrogant",
humor:"the quality of being funny",
hundred:"the number 100",
hunger:"the feeling of needing food",
hunt:"to search for animals to catch",
hurry:"to move quickly",
hurt:"to cause pain",
husband:"a married man",
habitual:"done regularly",
harmony:"agreement or peace",
harsh:"rough or severe",
hatch:"to come out of an egg",
hazard:"a possible source of danger",
heap:"a pile of things",
heaven:"a place believed to be above the earth",
hedge:"a fence made of bushes",
helmet:"a protective covering for the head",
herd:"a group of animals",
hesitate:"to pause before doing something",
hidden:"kept out of sight",
highlight:"to make something stand out",
highway:"a main public road",
hike:"a long walk in nature",
hire:"to give someone a job",
historic:"important in history",
hollow:"empty inside",
honesty:"the quality of being truthful",
hook:"a curved piece used to catch things",
hopeful:"feeling full of hope",
horizontal:"parallel to the ground",
horror:"intense fear",
hostile:"unfriendly or aggressive",
hover:"to stay in the air in one place",
huge:"very large",
humiliate:"to make someone feel ashamed",
hunger:"a need for food",
hurdle:"an obstacle to overcome",
hurricane:"a very strong storm",
hurry:"to act quickly",
husky:"strong and heavy",
hydrogen:"a light chemical element",
hybrid:"a mixture of two different things",
hygiene:"practices for cleanliness",
hypothesis:"an idea that can be tested",
heroic:"brave and courageous",
handshake:"a greeting by holding hands",
handful:"a small amount that fits in the hand",
headache:"pain in the head",
headline:"the title of a news article",
heartbeat:"the rhythm of the heart",
homeland:"a person's native country",
homework:"school work done at home",
ice:"frozen water",
idea:"a thought or suggestion",
ideal:"perfect or most suitable",
identify:"to recognize who or what something is",
identity:"who a person is",
idle:"not active or working",
ignore:"to refuse to pay attention",
ill:"sick or unhealthy",
illegal:"against the law",
image:"a picture or visual representation",
imagine:"to form a picture in the mind",
impact:"a strong effect",
impatient:"not willing to wait",
imply:"to suggest something indirectly",
important:"having great value or meaning",
impress:"to cause admiration",
improve:"to make something better",
impulse:"a sudden strong desire",
inch:"a small unit of length",
include:"to contain as part of something",
income:"money earned from work",
increase:"to become larger",
indeed:"in fact or truly",
independent:"free from control of others",
index:"a list of items in a book",
indicate:"to point out or show",
individual:"a single person or thing",
industry:"business activity of producing goods",
inevitable:"certain to happen",
infant:"a very young child",
infect:"to spread disease",
influence:"power to affect something",
inform:"to give information",
information:"facts or knowledge",
ingredient:"a part used in making food",
initial:"first or beginning",
injure:"to hurt someone physically",
injury:"physical harm",
inner:"inside or internal",
innocent:"not guilty of wrongdoing",
input:"information put into a system",
inquiry:"a request for information",
insect:"a small animal with six legs",
inside:"the inner part",
insist:"to demand something firmly",
inspect:"to examine carefully",
inspire:"to fill someone with motivation",
install:"to put something in place for use",
instance:"an example of something",
instant:"happening immediately",
instead:"in place of something else",
instruct:"to teach or direct",
instrument:"a tool or device",
insult:"to speak disrespectfully",
insurance:"protection against financial loss",
intact:"complete and undamaged",
intense:"very strong",
intent:"purpose or plan",
interest:"curiosity or attention",
interfere:"to get involved in a harmful way",
internal:"inside something",
international:"between different countries",
internet:"a global computer network",
interpret:"to explain the meaning",
interrupt:"to stop something briefly",
interval:"a space between things",
interview:"a meeting to ask questions",
introduce:"to present someone or something",
invent:"to create something new",
invest:"to put money into something",
investigate:"to examine carefully",
invite:"to ask someone to come",
involve:"to include something as part",
iron:"a strong metal element",
island:"land surrounded by water",
isolate:"to separate from others",
issue:"an important topic or problem",
item:"a single thing",
ivory:"a hard white material from animal teeth",
idealism:"belief in high values",
identical:"exactly the same",
ignite:"to start burning",
ignorance:"lack of knowledge",
illusion:"something that seems real but is not",
illustrate:"to explain with pictures or examples",
imitate:"to copy someone",
immense:"extremely large",
immortal:"living forever",
immune:"protected from disease",
implement:"to put a plan into action",
import:"to bring goods from another country",
impose:"to force something on others",
impression:"an idea formed about something",
impressive:"causing admiration",
improper:"not correct or suitable",
improve:"to make better",
improvement:"a positive change",
impurity:"something that makes something dirty",
innovation:"a new idea or method",
insight:"deep understanding",
integrate:"to combine into one group",
intellect:"the ability to think and reason",
jab:"to push suddenly with something sharp",
jacket:"a short coat worn on the upper body",
jail:"a place where criminals are kept",
jam:"a sweet fruit spread",
jar:"a glass container with a lid",
jaw:"the bone that holds the teeth",
jazz:"a style of music with strong rhythm",
jealous:"feeling envy of someone",
jeans:"pants made from strong denim cloth",
jet:"a fast aircraft powered by engines",
jewel:"a precious stone used in jewelry",
jewelry:"decorative items worn on the body",
job:"work done to earn money",
join:"to connect or come together",
joint:"a place where two bones meet",
joke:"something said to make people laugh",
journal:"a diary or written record",
journey:"travel from one place to another",
joy:"a feeling of great happiness",
judge:"a person who decides cases in court",
judgment:"a decision made after thinking",
juice:"liquid from fruits or vegetables",
jump:"to push the body into the air",
jungle:"a dense tropical forest",
junior:"a younger person",
jury:"a group that decides a court case",
justice:"fair treatment according to law",
justify:"to show something is right",
jolt:"a sudden movement or shock",
jolly:"very happy and cheerful",
jog:"to run slowly for exercise",
jogger:"a person who jogs",
jot:"to write something quickly",
jovial:"cheerful and friendly",
joyful:"full of happiness",
joyous:"very happy",
jigsaw:"a puzzle made of pieces",
jingle:"a short catchy song",
jolt:"a sudden shock",
jubilant:"feeling great joy",
jubilee:"a special celebration",
judicial:"related to courts of law",
jug:"a container for liquids",
jumble:"a confused mixture",
jumper:"a person or thing that jumps",
junction:"a place where roads meet",
juncture:"a particular point in time",
jungleland:"land covered with jungle",
juniper:"a type of evergreen plant",
junk:"old or useless items",
junkyard:"a place where old vehicles are kept",
juror:"a member of a jury",
jurisdiction:"the authority of a court",
jurisprudence:"the study of law",
just:"fair and reasonable",
justice:"moral fairness",
justification:"a good reason for something",
justify:"to prove something right",
jut:"to stick out",
juvenile:"young or not fully grown",
juxtapose:"to place things side by side",
javelin:"a spear used in sports",
jade:"a green precious stone",
jargon:"special words used in a profession",
jaunt:"a short pleasant trip",
jazzy:"bright and lively",
jeer:"to mock someone loudly",
jerk:"a sudden sharp movement",
jest:"to joke",
jester:"a person who entertains with jokes",
jiffy:"a very short time",
jitter:"nervous shaking",
jockey:"a rider of racehorses",
jocular:"fond of joking",
joist:"a beam used in building floors",
jolt:"a sudden shake",
journalist:"a person who writes news",
joust:"a medieval contest with spears",
joyride:"a ride taken for pleasure",
judicious:"showing good judgment",
juggernaut:"a powerful force",
jumpstart:"to start quickly",
junctional:"related to a joining point",
junglelike:"similar to a jungle",
juniority:"state of being younger",
junta:"a group ruling after a coup",
juridical:"related to law",
justly:"in a fair way",
justness:"quality of fairness",
juvenescence:"state of being youthful",
juxtaposition:"placing things side by side",
jadeite:"a form of jade",
jagged:"having rough sharp edges",
jamb:"side of a door frame",
jangle:"harsh ringing sound",
jasmine:"a fragrant flower",
jaunty:"lively and cheerful",
jeopardy:"danger of loss or harm",
jetty:"a structure built into water",
jingoism:"extreme patriotism",
jovian:"related to the planet Jupiter",
jubilation:"a feeling of great happiness",
keen:"very interested or eager",
keep:"to hold or continue having something",
kettle:"a container used for boiling water",
key:"a small tool used to open locks",
keyboard:"a set of keys used to type",
kick:"to hit something with the foot",
kid:"a young child",
kidnap:"to take someone away illegally",
kidney:"an organ that cleans blood",
kill:"to cause death",
kind:"friendly and helpful",
kindness:"the quality of being kind",
king:"a male ruler of a country",
kingdom:"a country ruled by a king",
kiss:"to touch with the lips",
kitchen:"a room where food is prepared",
kite:"a toy flown in the wind",
kitten:"a young cat",
knee:"the joint between thigh and leg",
kneel:"to rest on the knees",
knife:"a sharp tool used for cutting",
knight:"a warrior in medieval times",
knit:"to make cloth using yarn",
knob:"a round handle for opening doors",
knock:"to hit a surface to make a sound",
knot:"a fastening made by tying rope",
know:"to understand or be aware",
knowledge:"facts or information learned",
known:"recognized or familiar",
koala:"an Australian tree-dwelling animal",
krypton:"a chemical element",
kale:"a green leafy vegetable",
karate:"a Japanese form of self-defense",
kayak:"a small narrow boat",
keenly:"with great interest",
keenness:"strong interest",
kernel:"the inner part of a seed",
ketchup:"a tomato sauce",
keyhole:"a hole where a key is inserted",
keystone:"the central supporting stone",
kickoff:"the start of an event",
kidney:"an organ in the body",
kindhearted:"having a kind nature",
kindle:"to start a fire",
kindly:"in a gentle way",
kindred:"related by family",
kinetic:"related to motion",
kinship:"family relationship",
kiosk:"a small shop or booth",
kitchenware:"tools used in a kitchen",
kitsch:"art considered poor taste",
kitbag:"a bag for carrying equipment",
knapsack:"a bag carried on the back",
knave:"a dishonest man",
kneecap:"the bone at the front of the knee",
knelt:"past form of kneel",
knighthood:"rank of a knight",
knockout:"a decisive victory",
knotty:"full of knots or problems",
knowing:"showing knowledge",
knowledgeable:"having much knowledge",
kudos:"praise for an achievement",
karyotype:"the number and appearance of chromosomes",
kinesiology:"study of body movement",
kilogram:"a unit of mass",
kilometer:"a unit of distance",
kilowatt:"a unit of power",
kindredness:"state of being related",
kindliness:"quality of kindness",
kitchenette:"a small kitchen",
kingly:"like a king",
kingpin:"a very important person",
kinsman:"a male relative",
kinfolk:"family members",
kirsch:"a cherry-flavored drink",
kilt:"a traditional Scottish skirt",
kiln:"a furnace for firing pottery",
kibble:"small pieces of food",
kink:"a twist or curve",
kinked:"bent sharply",
kittenish:"playful like a kitten",
knobby:"full of knobs",
knackered:"very tired",
knaveish:"dishonest",
knitting:"making fabric with yarn",
knoll:"a small hill",
knockdown:"forceful defeat",
knotted:"tied with knots",
knucklebone:"bone of the finger",
knuckle:"joint of the finger",
knucklehead:"a foolish person",
kook:"a strange person",
kooky:"strange or odd",
kosher:"prepared according to Jewish law",
krypton:"a colorless gas element",
kaleidoscope:"a tube that shows changing patterns",
karma:"the idea that actions affect future events",
label:"a tag that gives information",
labor:"physical or mental work",
lack:"to not have enough of something",
ladder:"a structure used for climbing",
lady:"a polite term for a woman",
lake:"a large area of water surrounded by land",
lamp:"a device that produces light",
land:"the solid part of the earth",
language:"a system used for communication",
large:"big in size",
last:"coming after all others",
late:"after the expected time",
laugh:"to show happiness with sound",
launch:"to start or send off",
law:"rules made by a government",
lawn:"an area of grass near a house",
layer:"a level or thickness of something",
lead:"to guide someone",
leader:"a person who directs others",
leaf:"a flat green part of a plant",
league:"a group of teams competing",
lean:"to bend or rest against something",
learn:"to gain knowledge",
least:"the smallest amount",
leave:"to go away from a place",
lecture:"a talk given to teach something",
left:"the opposite of right",
leg:"a limb used for walking",
legal:"allowed by law",
legend:"a traditional story",
leisure:"free time for relaxation",
lemon:"a sour yellow fruit",
lend:"to give something to be returned",
length:"measurement of how long something is",
less:"a smaller amount",
lesson:"something learned or taught",
letter:"a written message or alphabet symbol",
level:"a flat or equal height",
liar:"a person who tells lies",
liberty:"freedom from control",
library:"a place where books are kept",
license:"official permission",
life:"the state of living",
lift:"to raise something",
light:"brightness or something not heavy",
like:"to enjoy something",
limit:"the highest or lowest point allowed",
line:"a long narrow mark",
link:"a connection between things",
lion:"a large wild cat",
liquid:"a substance that flows",
list:"a group of items written together",
listen:"to pay attention to sound",
literature:"written works such as books",
little:"small in size",
live:"to be alive",
load:"something carried or transported",
loan:"money borrowed from someone",
local:"related to a nearby place",
lock:"a device for closing something",
log:"a large piece of wood",
logic:"reasoning based on facts",
lonely:"feeling alone and sad",
long:"measuring a great distance",
look:"to direct eyes toward something",
loose:"not tight or fixed",
lord:"a person with power or authority",
lose:"to fail to keep something",
loss:"the act of losing",
loud:"making a strong sound",
love:"a strong feeling of affection",
low:"not high",
loyal:"faithful and devoted",
luck:"success by chance",
lucky:"having good luck",
lunch:"a meal eaten at midday",
lung:"an organ used for breathing",
luxury:"something expensive and comfortable",
laboratory:"a place for scientific experiments",
landscape:"a view of natural scenery",
landlord:"a person who rents property",
lane:"a narrow road",
language:"a system of words for communication",
latitude:"distance north or south of the equator",
laughter:"the sound of laughing",
launchpad:"a place for launching rockets",
lawyer:"a person who practices law",
layout:"the arrangement of parts",
leadership:"the act of leading",
leaflet:"a small printed sheet",
learning:"the process of gaining knowledge",
legacy:"something handed down from the past",
legalize:"to make something lawful",
legislation:"laws made by a government",
lendable:"able to be lent",
lengthen:"to make longer",
liberate:"to set free",
lifelong:"lasting for life",
lifeline:"something that provides help",
lighten:"to make lighter",
likeness:"similar appearance",
limestone:"a type of rock",
limitation:"a restriction or boundary",
lively:"full of life and energy",
livestock:"farm animals",
locate:"to find the position of something",
location:"a place where something is",
logical:"based on clear reasoning",
longevity:"long life",
loophole:"a small gap in rules",
loyalty:"faithfulness to someone",
machine:"a device that performs work",
mad:"very angry",
magic:"special power that seems impossible",
magnet:"an object that attracts iron",
mail:"letters and packages sent by post",
main:"most important",
major:"very important or large",
make:"to create something",
male:"relating to a man or boy",
mall:"a large shopping center",
man:"an adult male person",
manage:"to control or organize",
manager:"a person who directs a business",
manner:"the way something is done",
many:"a large number",
map:"a drawing of a place",
march:"to walk in a steady way",
mark:"a visible sign or symbol",
market:"a place where goods are sold",
marry:"to become husband and wife",
mass:"a large amount",
master:"a person with great skill",
match:"a contest between people or teams",
material:"substance used to make things",
math:"the study of numbers",
matter:"a subject or issue",
maximum:"the greatest amount",
may:"used to show possibility",
meal:"food eaten at a particular time",
mean:"to intend or express something",
meaning:"what something represents",
measure:"to find size or amount",
meat:"food from animal flesh",
mechanic:"a person who repairs machines",
media:"means of communication like TV or newspapers",
medical:"related to medicine",
medicine:"a substance used to treat illness",
meet:"to come together",
meeting:"an event where people gather",
member:"a person in a group",
memory:"ability to remember",
mention:"to speak about briefly",
menu:"a list of food choices",
message:"information sent to someone",
metal:"a hard shiny material",
method:"a way of doing something",
middle:"the center part",
might:"great strength or power",
mile:"a unit of distance",
milk:"a white liquid from cows",
mind:"the part that thinks and feels",
mine:"belonging to me",
minute:"a unit of time equal to sixty seconds",
mirror:"a surface that reflects images",
miss:"to fail to reach something",
mission:"a special task",
mistake:"an error",
mix:"to combine things together",
model:"a small copy or example",
modern:"relating to present times",
moment:"a very short time",
money:"coins or notes used to buy things",
month:"a period of about thirty days",
moon:"the natural satellite of Earth",
moral:"relating to right and wrong",
more:"a greater amount",
morning:"the early part of the day",
most:"the greatest amount",
mother:"a female parent",
motion:"movement",
motor:"a machine that produces motion",
mountain:"a very high hill",
mouse:"a small animal or computer device",
mouth:"the opening in the face used for eating",
move:"to change position",
movie:"a film shown for entertainment",
much:"a large amount",
music:"organized sounds for listening",
must:"used to show necessity",
mutual:"shared by two sides",
mystery:"something difficult to understand",
magazine:"a printed publication with articles",
magnify:"to make something appear larger",
maintain:"to keep in good condition",
majority:"more than half",
manufacture:"to produce goods in large numbers",
margin:"the edge of a page",
marine:"related to the sea",
marvel:"something amazing",
mature:"fully grown or developed",
medal:"a metal award",
meditate:"to think deeply",
melt:"to change from solid to liquid",
mercy:"kindness toward someone",
merge:"to combine into one",
migrate:"to move from one place to another",
mineral:"a natural substance in the earth",
minor:"less important",
miracle:"an amazing event that seems impossible",
moderate:"not too much or too little",
monument:"a structure built to remember something",
name:"a word used to identify a person or thing",
narrow:"not wide",
nation:"a large group of people living in one country",
national:"relating to a nation",
native:"a person born in a particular place",
natural:"existing in nature",
nature:"the physical world and living things",
navy:"the military force that fights at sea",
near:"close in distance",
neat:"clean and orderly",
necessary:"needed or required",
neck:"the part connecting head and body",
need:"to require something",
needle:"a thin pointed tool for sewing",
negative:"expressing no or denial",
neighbor:"a person living nearby",
neither:"not one nor the other",
nerve:"a fiber carrying signals in the body",
nervous:"feeling worried or afraid",
nest:"a structure where birds lay eggs",
net:"a material made of threads with holes",
network:"a group of connected things",
neutral:"not supporting either side",
never:"not at any time",
new:"not old",
news:"information about recent events",
newspaper:"a printed publication of news",
next:"coming immediately after",
nice:"pleasant and kind",
night:"the time of darkness",
nine:"the number after eight",
noisy:"making a lot of sound",
none:"not any",
normal:"usual or typical",
north:"the direction opposite south",
nose:"the part of the face used for smelling",
note:"a short written record",
nothing:"not anything",
notice:"to become aware of something",
noun:"a word that names a person, place, or thing",
novel:"a long fictional story",
number:"a symbol used for counting",
nurse:"a person who cares for sick people",
nut:"a hard-shelled fruit",
nuclear:"relating to the nucleus of an atom",
nuisance:"something annoying",
numeral:"a symbol representing a number",
nutrition:"the process of getting food for health",
nylon:"a strong synthetic fiber",
narrate:"to tell a story",
narration:"the act of telling a story",
narrative:"a spoken or written story",
nationality:"the status of belonging to a nation",
navigation:"the process of directing movement",
navigator:"a person who directs travel",
neatly:"in a tidy way",
necessity:"something essential",
neglect:"to fail to care for properly",
negotiate:"to discuss to reach agreement",
neighborly:"friendly to neighbors",
nephew:"the son of one's sibling",
nevertheless:"in spite of that",
nickname:"an informal name",
nineteen:"the number after eighteen",
ninety:"the number after eighty-nine",
noble:"having high moral qualities",
nobody:"no person",
nod:"to move the head up and down",
noise:"a sound especially if loud",
nominate:"to suggest someone for a role",
nonstop:"without stopping",
nonsense:"words with no meaning",
normality:"the state of being normal",
northward:"toward the north",
nostalgia:"a feeling of longing for the past",
notable:"worthy of attention",
notebook:"a book for writing notes",
notion:"an idea or belief",
notify:"to inform someone",
notorious:"famous for something bad",
novice:"a beginner",
nowhere:"no place",
nurture:"to care for and help grow",
nutrient:"a substance that provides nourishment",
nymph:"a mythological nature spirit",
numerous:"many in number",
numeric:"related to numbers",
narrowly:"with little space or margin",
nationwide:"across an entire country",
naturalize:"to grant citizenship",
necklace:"a piece of jewelry worn around the neck",
needless:"unnecessary",
negativity:"the state of being negative",
neon:"a chemical element used in lights",
nerd:"a person very interested in studies",
neutrality:"the state of not taking sides",
nibble:"to take small bites",
nightmare:"a frightening dream",
nomad:"a person who moves from place to place",
noteworthy:"deserving attention",
oak:"a large strong tree",
oar:"a long pole used to row a boat",
oasis:"a fertile place in a desert with water",
oath:"a serious promise",
obey:"to follow rules or commands",
object:"a thing that can be seen or touched",
objective:"a goal or purpose",
oblige:"to help or do a favor",
observe:"to watch carefully",
obtain:"to get something",
obvious:"easy to see or understand",
occasion:"a special event",
occupy:"to take up space",
occur:"to happen",
ocean:"a very large body of salt water",
odd:"strange or unusual",
offend:"to upset or hurt someone's feelings",
offer:"to present something for acceptance",
office:"a place where work is done",
officer:"a person with authority",
official:"approved by authority",
often:"many times",
oil:"a thick liquid from plants or animals",
old:"having lived for many years",
olive:"a small green or black fruit",
omit:"to leave something out",
once:"one time",
one:"the number after zero",
ongoing:"continuing to happen",
onion:"a vegetable with layers",
online:"connected to the internet",
only:"just one and no more",
open:"not closed",
operate:"to control how something works",
opinion:"a personal belief or view",
opponent:"a person who competes against another",
opportunity:"a chance to do something",
oppose:"to be against something",
opposite:"completely different",
optimize:"to make something as good as possible",
option:"a choice",
orange:"a citrus fruit or a color",
orbit:"the path of a planet around a star",
order:"to arrange or request something",
ordinary:"common or usual",
organ:"a body part with a special function",
organic:"related to living things",
organize:"to arrange in order",
origin:"the beginning of something",
original:"the first form of something",
other:"different or additional",
otherwise:"in a different way",
ought:"used to express duty",
ounce:"a small unit of weight",
our:"belonging to us",
outcome:"the final result",
outdoor:"happening outside",
outer:"on the outside",
outline:"a general description",
output:"the result produced",
outside:"the outer side",
oval:"a shape like an egg",
oven:"a device used for baking",
over:"above or across",
overall:"including everything",
overcome:"to succeed against difficulty",
overflow:"to spill over the edge",
overlook:"to fail to notice",
overnight:"during the night",
owe:"to need to pay or repay",
own:"to possess something",
owner:"a person who owns something",
oxygen:"a gas needed for breathing",
obedience:"the act of following rules",
obligation:"a duty or responsibility",
observation:"the act of watching carefully",
obstacle:"something that blocks progress",
occupation:"a job or profession",
occurrence:"something that happens",
offense:"an act that breaks a rule",
offshore:"away from the coast",
offspring:"a person's children",
ointment:"a smooth medicine for skin",
oldness:"the state of being old",
omission:"something left out",
omnivore:"an animal that eats plants and meat",
onward:"moving forward",
opening:"the act of making something open",
operation:"the process of working",
operator:"a person who runs a machine",
oppression:"cruel control over people",
optical:"related to sight",
orchestra:"a large group of musicians",
orientation:"the act of finding direction",
ornament:"a decorative object",
outbreak:"a sudden start of something",
outfit:"a set of clothes",
outlet:"a place to release something",
outlook:"a general attitude or view",
outrage:"great anger",
outstanding:"extremely good",
overhead:"above the head",
overload:"too much of something",
override:"to cancel a decision",
oversee:"to supervise work",
overtime:"extra working time",
pack:"to put things into a container",
page:"one side of a sheet of paper",
pain:"a feeling of physical suffering",
paint:"to apply color to a surface",
pair:"two things that belong together",
palace:"a large and impressive house",
pale:"light in color",
pan:"a metal container used for cooking",
panel:"a flat piece forming part of a surface",
panic:"sudden strong fear",
paper:"material used for writing",
parade:"a public procession",
parcel:"a package sent by mail",
parent:"a father or mother",
park:"a public green area",
part:"a piece of something",
partner:"a person who shares an activity",
party:"a social gathering",
pass:"to move past something",
passage:"a path or corridor",
passenger:"a person traveling in a vehicle",
passion:"a strong feeling",
past:"time before now",
path:"a small road or track",
patient:"a person receiving medical care",
pattern:"a repeated design",
pause:"a short stop",
pay:"to give money for something",
peace:"a state without war",
peak:"the highest point",
pen:"a tool used for writing",
pencil:"a tool for writing or drawing",
people:"human beings",
pepper:"a spicy seasoning",
perfect:"having no mistakes",
perform:"to carry out an action",
perhaps:"maybe or possibly",
period:"a length of time",
permit:"to allow something",
person:"a human individual",
pet:"an animal kept for companionship",
phase:"a stage in development",
phone:"a device used to talk over distance",
photo:"a picture taken with a camera",
phrase:"a group of words",
physical:"related to the body",
piano:"a musical instrument with keys",
pick:"to choose something",
picture:"an image or drawing",
piece:"a small part of something",
pile:"a group of things placed together",
pilot:"a person who flies an aircraft",
pin:"a small pointed object",
pipe:"a tube for carrying liquid or gas",
place:"a location or area",
plan:"a detailed idea of how to do something",
planet:"a large object orbiting a star",
plant:"a living organism that grows in soil",
plastic:"a light material made by chemicals",
plate:"a flat dish used for food",
play:"to take part in an activity for fun",
pleasant:"giving a feeling of happiness",
please:"to make someone happy",
plenty:"a large amount",
plot:"the main story of a book or movie",
plug:"a device for connecting electricity",
plus:"added to something",
pocket:"a small pouch in clothing",
poem:"a piece of writing expressing feelings",
poet:"a person who writes poems",
point:"a sharp end or specific place",
police:"people who enforce the law",
policy:"a plan or rule",
polite:"showing good manners",
pool:"a small body of water",
poor:"having little money",
popular:"liked by many people",
population:"the number of people in an area",
position:"a place or location",
positive:"showing good attitude",
possess:"to own something",
possible:"able to happen",
post:"to send or place something",
pot:"a container used for cooking",
power:"ability to do something",
practice:"repeated exercise to improve skill",
praise:"to express approval",
pray:"to speak to a god",
predict:"to say what will happen",
prefer:"to like something more",
prepare:"to get ready",
present:"a gift or something given",
press:"to push something",
prevent:"to stop something from happening",
price:"the cost of something",
pride:"a feeling of satisfaction",
primary:"most important or first",
prime:"of the best quality",
print:"to produce text or images",
priority:"something more important than others",
prison:"a place where criminals are kept",
private:"not public",
problem:"a difficult situation",
process:"a series of actions",
produce:"to create or make something",
product:"something made or produced",
profit:"money gained from business",
quality:"the standard of something",
quantity:"the amount or number of something",
quarter:"one of four equal parts",
queen:"a female ruler of a country",
question:"a sentence used to ask something",
quick:"moving or happening fast",
quiet:"making little or no noise",
quit:"to stop doing something",
quiz:"a short test",
quote:"to repeat someone else's words",
quack:"the sound made by a duck",
quad:"a group of four",
quail:"a small bird",
quake:"a shaking of the ground",
qualification:"a skill or ability needed for a job",
qualify:"to become suitable for something",
qualitative:"relating to quality not numbers",
quantify:"to measure the amount of something",
quarantine:"isolation to prevent disease spread",
quarrel:"an angry argument",
quarry:"a place where stone is dug",
quarterly:"happening every three months",
quartz:"a hard mineral",
quench:"to satisfy thirst",
query:"a question or request for information",
quest:"a long search for something",
queue:"a line of people waiting",
quickly:"in a fast way",
quickness:"the quality of being fast",
quietly:"in a silent way",
quietness:"the state of being calm",
quill:"a feather used for writing",
quilt:"a warm bed covering",
quince:"a yellow fruit",
quirk:"a strange habit",
quitters:"people who stop trying",
quota:"a fixed share or amount",
quotation:"a repeated statement",
quotient:"the result of division",
quasar:"a very bright object in space",
quenchable:"able to be satisfied",
quibble:"to argue about small details",
quickstep:"a fast dance",
quicknesses:"states of being fast",
quiescent:"inactive or quiet",
quillpen:"a pen made from a feather",
quilted:"stitched with padding",
quintet:"a group of five musicians",
quintuple:"five times as many",
quirky:"having unusual traits",
quiver:"to shake slightly",
quizzical:"showing confusion",
quorum:"minimum members needed for a meeting",
quenchless:"impossible to satisfy",
questionable:"doubtful or uncertain",
questioning:"asking questions",
quicklime:"a chemical form of lime",
quicknessful:"full of speed",
quietude:"a state of calm",
quiltmaker:"a person who makes quilts",
quintessence:"the perfect example of something",
quirkiness:"the quality of being quirky",
quiveringly:"with slight shaking",
quizzing:"asking questions",
quotable:"worth repeating",
quadrangle:"a four-sided area",
quadrant:"one quarter of a circle",
quadratic:"related to square numbers",
quadruple:"four times as much",
qualificationtest:"an exam to prove ability",
qualitycontrol:"checking product standards",
quantitysurvey:"measurement of materials",
quarantinezone:"an isolated area",
quarterback:"a leader player in American football",
quarterdeck:"upper deck of a ship",
quarterfinal:"a competition round",
quartermaster:"a military supply officer",
quartzite:"a hard rock",
quasarbeam:"energy from a quasar",
quenchwater:"water used to cool metal",
querylanguage:"a computer database language",
quester:"one who searches",
queueing:"forming a line",
quickbread:"bread made quickly",
quickfire:"very rapid",
quickfreeze:"to freeze rapidly",
quickmatch:"a fast contest",
quickrelease:"easy to remove",
quickscan:"a fast examination",
quickview:"a short look",
quietplace:"a silent area",
quillwork:"decoration with quills",
quincepaste:"a food made from quince fruit",
quirksome:"full of odd behavior",
quivering:"trembling slightly",
quizmaster:"person who asks quiz questions",
quorumrule:"rule for meeting members",
quotebook:"a collection of quotes",
quotefeed:"a stream of quotations",
rabbit:"a small animal with long ears",
race:"a competition of speed",
radio:"a device that receives sound signals",
rain:"water falling from clouds",
raise:"to lift something up",
range:"a group or series of things",
rapid:"very fast",
rare:"not common",
rate:"a measure or speed of something",
rather:"to some degree",
reach:"to arrive at something",
react:"to respond to something",
read:"to look at and understand words",
ready:"prepared for something",
real:"true or actual",
reason:"a cause or explanation",
receive:"to get something",
recent:"happening not long ago",
recognize:"to identify something known",
record:"to store information",
reduce:"to make smaller",
refer:"to mention something",
reflect:"to show or think about something",
refuse:"to say no to something",
regard:"to consider or think about",
region:"a particular area",
register:"to officially record something",
regret:"to feel sorry about something",
regular:"happening often",
reject:"to refuse to accept",
relate:"to connect with something",
relax:"to become calm",
release:"to set free",
rely:"to depend on someone",
remain:"to stay the same",
remark:"a spoken comment",
remember:"to keep in memory",
remove:"to take away",
repair:"to fix something",
repeat:"to do again",
replace:"to put something instead of another",
reply:"to answer someone",
report:"information about something",
represent:"to stand for something",
request:"to ask for something",
require:"to need something",
rescue:"to save from danger",
research:"careful study to learn something",
reserve:"to keep something for later",
resist:"to oppose something",
resolve:"to solve a problem",
respect:"a feeling of admiration",
respond:"to answer or react",
rest:"to relax or stop working",
result:"the outcome of something",
return:"to go back",
reveal:"to show something hidden",
review:"to examine again",
reward:"something given for good work",
rhythm:"a pattern of sounds",
rice:"a common grain food",
rich:"having a lot of money",
ride:"to travel on something",
right:"correct or proper",
ring:"a circular band",
rise:"to move upward",
risk:"a chance of danger",
river:"a large flowing stream of water",
road:"a path for vehicles",
roar:"a loud deep sound",
rock:"a hard natural stone",
role:"a part played by someone",
roll:"to move by turning",
roof:"the top covering of a building",
room:"a space inside a building",
root:"the part of a plant in soil",
rope:"a thick strong cord",
rough:"not smooth",
round:"shaped like a circle",
route:"a path or direction",
rule:"a principle or instruction",
run:"to move quickly on foot",
rural:"relating to the countryside",
rush:"to move very quickly",
rust:"a reddish coating on iron",
rabbitry:"a place where rabbits are kept",
radiation:"energy traveling through space",
radical:"extreme or fundamental change",
raffle:"a lottery for prizes",
ragged:"torn or worn out",
rail:"a metal bar for trains",
rainbow:"a colored arc in the sky",
random:"without a pattern",
rapidly:"very quickly",
rapture:"a feeling of great joy",
rarely:"not often",
rash:"an area of irritated skin",
ratio:"a comparison of numbers",
reactor:"a device producing nuclear energy",
readable:"easy to read",
realize:"to understand something clearly",
rebuild:"to build again",
recall:"to remember",
recharge:"to fill with power again",
recycle:"to reuse materials",
redo:"to do again",
refine:"to improve something",
refresh:"to make fresh again",
reform:"to make changes for improvement",
safe:"free from danger",
sail:"to travel on water using a boat",
salt:"a white mineral used for flavor",
same:"not different",
sand:"small grains of rock",
save:"to keep something safe",
say:"to speak words",
scale:"a system of measurement",
scan:"to examine quickly",
scar:"a mark left after a wound heals",
scene:"a place where something happens",
school:"a place for learning",
science:"study of nature and knowledge",
score:"points gained in a game",
scratch:"to rub with nails",
screen:"a surface for displaying images",
sea:"a large body of salt water",
search:"to look for something",
season:"a period of the year",
seat:"a place to sit",
second:"a unit of time or next after first",
secret:"something kept hidden",
section:"a part of something",
secure:"safe and protected",
see:"to use the eyes",
seed:"a small plant part that grows",
seek:"to try to find",
seem:"to appear to be",
select:"to choose something",
self:"a person's own being",
sell:"to exchange something for money",
send:"to cause something to go",
sense:"ability to feel or understand",
sentence:"a group of words expressing a thought",
separate:"to divide things apart",
series:"a number of things in order",
serious:"important and not joking",
serve:"to provide service",
service:"work done for others",
set:"to put something in place",
settle:"to come to rest",
seven:"the number after six",
several:"more than two but not many",
shade:"an area protected from light",
shadow:"a dark shape made by blocking light",
shake:"to move back and forth",
shall:"used to express future action",
shape:"the form of something",
share:"to give part to others",
sharp:"having a fine point",
sheep:"a farm animal with wool",
sheet:"a large thin piece of material",
shelf:"a flat support for objects",
shell:"a hard outer covering",
shift:"to move slightly",
shine:"to give bright light",
ship:"a large boat",
shirt:"a piece of clothing",
shock:"a sudden surprise",
shoe:"footwear for protection",
shoot:"to fire or send out",
shop:"a place to buy things",
shore:"land next to water",
short:"not long",
should:"used to show duty",
shoulder:"the joint connecting arm and body",
shout:"to speak very loudly",
show:"to display something",
shut:"to close something",
side:"a position to the left or right",
sign:"a symbol or mark",
signal:"a sign used to communicate",
silent:"making no sound",
silver:"a shiny gray metal",
simple:"easy to understand",
since:"from a past time until now",
sing:"to make musical sounds",
single:"only one",
sink:"to go down below surface",
sister:"a female sibling",
sit:"to rest on a seat",
site:"a place where something is located",
size:"how big something is",
skill:"ability gained through practice",
skin:"the outer covering of the body",
sky:"the space above the earth",
sleep:"to rest with eyes closed",
slide:"to move smoothly",
slow:"not fast",
small:"little in size",
smart:"quick to learn or understand",
smell:"the sense of detecting odors",
smile:"a happy facial expression",
smoke:"gas produced by burning",
smooth:"even and not rough",
snow:"frozen water falling from sky",
soak:"to make something very wet",
social:"relating to society",
soft:"not hard",
soil:"earth where plants grow",
solid:"firm and not liquid",
table:"a piece of furniture with a flat top",
tackle:"to deal with a problem",
tail:"the rear part of an animal",
take:"to get or receive something",
talent:"natural ability to do something well",
talk:"to speak with someone",
tall:"having great height",
tank:"a large container for liquid",
tap:"to hit lightly",
target:"a goal or aim",
task:"a piece of work to be done",
taste:"the sense of flavor",
tax:"money paid to the government",
teach:"to give knowledge or instruction",
team:"a group working together",
tear:"a drop of liquid from the eye",
technical:"related to machines or technology",
technique:"a special way of doing something",
technology:"the use of science for practical purposes",
teen:"a person aged between 13 and 19",
telephone:"a device used to talk over distance",
television:"a device for watching moving pictures",
tell:"to give information",
temperature:"how hot or cold something is",
temple:"a building for worship",
temporary:"lasting for a short time",
ten:"the number after nine",
tend:"to take care of something",
tennis:"a sport played with rackets",
tense:"a grammatical form showing time",
term:"a word or period of time",
test:"an examination of knowledge",
text:"written or printed words",
thank:"to express gratitude",
theater:"a place for plays or movies",
theme:"the main subject",
theory:"an idea used to explain something",
there:"in that place",
thick:"having large distance between sides",
thin:"not thick",
thing:"an object or item",
think:"to use the mind",
third:"coming after second",
thirst:"a need to drink water",
thirty:"the number after twenty-nine",
this:"referring to something near",
thought:"an idea in the mind",
thread:"a thin strand used for sewing",
threat:"a statement of possible harm",
three:"the number after two",
throat:"the front part of the neck",
through:"moving from one side to another",
throw:"to send something through the air",
thumb:"the short thick finger",
thunder:"a loud sound during a storm",
ticket:"a printed pass for entry",
tide:"the rise and fall of sea levels",
tie:"to fasten something with string",
tight:"firmly fixed",
time:"a measurement of events",
tiny:"very small",
tip:"the pointed end of something",
tire:"a rubber covering for wheels",
title:"the name of a book or work",
today:"the present day",
toe:"one of the digits on a foot",
together:"with each other",
toilet:"a place for washing or using restroom",
tomato:"a red fruit used as a vegetable",
tomorrow:"the day after today",
tone:"the quality of a sound",
tongue:"the organ used for tasting",
tool:"an instrument for work",
tooth:"a hard part in the mouth for chewing",
topic:"the subject of discussion",
total:"the complete amount",
touch:"to feel with the hand",
tough:"strong and hard to break",
tour:"a journey for pleasure",
toward:"in the direction of",
tower:"a tall narrow building",
town:"a small city",
toy:"an object for children to play with",
track:"a path or course",
trade:"the buying and selling of goods",
tradition:"a custom passed through generations",
traffic:"vehicles moving on roads",
train:"a series of connected railway cars",
transfer:"to move something from one place to another",
transform:"to change in form",
translate:"to change language of words",
transport:"to carry something from one place to another",
travel:"to go from one place to another",
treat:"to behave toward someone",
treatment:"medical care given to a patient",
tree:"a large plant with a trunk",
trend:"a general direction of change",
trial:"a test or examination",
triangle:"a shape with three sides",
tribe:"a group of related people",
trick:"a clever action",
trip:"a short journey",
trouble:"difficulty or problems",
true:"correct or real",
trust:"belief in honesty",
truth:"the fact or reality",
try:"to attempt something",
tube:"a hollow cylinder",
tune:"a musical melody",
turn:"to move around an axis",
type:"a category or kind",
ugly:"unpleasant to look at",
umbrella:"a device used to protect from rain",
unable:"not capable of doing something",
uncertain:"not sure about something",
uncle:"the brother of one's parent",
uncommon:"not usual or rare",
uncover:"to remove a cover",
under:"below something",
undergo:"to experience something",
understand:"to know the meaning of something",
undertake:"to begin a task",
undo:"to reverse an action",
uneasy:"feeling worried",
unemployed:"without a job",
unequal:"not equal",
unexpected:"not planned or predicted",
unfair:"not just or equal",
unfold:"to open something that was folded",
unhappy:"not happy",
uniform:"clothing worn by members of a group",
union:"a joining together",
unique:"being the only one of its kind",
unit:"a single thing or group",
unite:"to join together",
universal:"relating to everyone",
universe:"all space and everything in it",
university:"a place of higher education",
unknown:"not known",
unless:"except if",
unlock:"to open a lock",
unlucky:"having bad luck",
unnecessary:"not needed",
unpack:"to remove things from a package",
unpleasant:"not enjoyable",
unpopular:"not liked by many",
unreal:"not real",
unsafe:"not safe",
unsure:"not certain",
until:"up to a certain time",
unusual:"not common",
update:"to make something more current",
upgrade:"to improve something",
uphold:"to support or maintain",
upkeep:"the act of maintaining",
upload:"to send data to a computer system",
upon:"on or immediately after",
upper:"higher in position",
upright:"standing straight",
upset:"unhappy or disturbed",
urban:"relating to a city",
urge:"to strongly encourage",
use:"to employ something",
useful:"helpful for a purpose",
useless:"not useful",
usual:"commonly done",
utility:"usefulness or service",
utilize:"to make use of",
utter:"to speak words",
ultimate:"the final or most important",
umbrellaed:"covered like an umbrella",
umpire:"a person who judges a game",
unablebodied:"not physically strong",
unarmed:"without weapons",
unaware:"not knowing",
unbalance:"to disturb balance",
unbelievable:"hard to believe",
unclear:"not easy to understand",
uncomfortable:"causing discomfort",
unconscious:"not awake",
underground:"beneath the earth",
underline:"to draw a line under text",
underneath:"below something",
underwater:"below the surface of water",
undivided:"not separated",
undoing:"the act of reversing something",
undoubtedly:"without doubt",
uneven:"not level",
unfolded:"opened out",
unfriendly:"not kind",
unhealthy:"not good for health",
unify:"to make one",
unimportant:"not significant",
unionize:"to form a union",
unison:"happening together",
united:"joined together",
unity:"the state of being one",
unload:"to remove cargo",
unlocking:"the act of opening a lock",
unlimited:"without limit",
unmatched:"having no equal",
unnatural:"not natural",
unnoticed:"not seen",
unoccupied:"not in use",
unofficial:"not formally approved",
unopened:"not yet opened",
unorganized:"not arranged",
unpaid:"not given money",
unpredictable:"not able to be predicted",
unprepared:"not ready",
unqualified:"not having required skill",
unrealistic:"not practical",
unstable:"not steady",
untidy:"not neat",
untrained:"not taught",
unusualness:"state of being unusual",
vacant:"empty or not occupied",
vacation:"a period of rest or travel",
vague:"not clear or certain",
valid:"legally or logically acceptable",
value:"the worth of something",
van:"a vehicle used to transport goods",
vanish:"to disappear suddenly",
variable:"something that can change",
variety:"a number of different types",
various:"several different kinds",
vast:"very large in size",
vegetable:"a plant used as food",
vehicle:"a machine used for transportation",
venture:"a risky or daring journey",
verb:"a word that describes an action",
verify:"to confirm truth",
version:"a particular form of something",
vertical:"standing straight up",
very:"to a high degree",
vessel:"a ship or container",
victim:"a person harmed by an event",
victory:"success in a competition",
video:"moving images recorded or broadcast",
view:"the ability to see something",
village:"a small group of houses",
violent:"using strong physical force",
virtual:"existing mainly on computers",
visible:"able to be seen",
vision:"the ability to see",
visit:"to go see someone",
visual:"related to sight",
vital:"very important",
vivid:"bright and clear",
voice:"the sound produced by speaking",
volume:"the amount of space something takes",
vote:"to choose in an election",
voyage:"a long journey by sea",
vacuum:"a space with no air",
validity:"the quality of being valid",
valuation:"the act of determining value",
vanilla:"a flavor from a tropical plant",
variation:"a change or difference",
vegetation:"plants growing in an area",
velocity:"speed in a direction",
vendor:"a person who sells goods",
venturecapital:"money invested in risky businesses",
verdict:"a decision made by a jury",
verification:"the process of confirming truth",
versatile:"able to do many things",
verse:"a line of poetry",
verticality:"the quality of being vertical",
veteran:"a person with long experience",
veto:"a power to reject a decision",
vibration:"a rapid movement back and forth",
vice:"a bad habit",
victorious:"having won a victory",
viewpoint:"a particular opinion",
vigorous:"strong and active",
villa:"a large country house",
violate:"to break a rule",
violation:"the act of breaking a rule",
violence:"physical force intended to harm",
virgin:"never used or untouched",
virtue:"moral goodness",
virus:"a tiny organism that causes disease",
visiblelight:"light visible to the human eye",
visionary:"a person with new ideas",
visualize:"to form a picture in the mind",
vocabulary:"a list of words",
vocal:"relating to the voice",
volcano:"a mountain that erupts lava",
voltage:"electric potential difference",
voluntary:"done by choice",
volunteer:"a person who helps freely",
vomit:"to throw up food from stomach",
vortex:"a spinning flow of fluid",
voyager:"a traveler",
vulture:"a large bird that eats dead animals",
vacillate:"to hesitate between choices",
valiant:"showing bravery",
validate:"to confirm accuracy",
valor:"great courage",
vandal:"a person who destroys property",
vanguard:"the leading position",
vantage:"a good position for viewing",
varnish:"a liquid coating for protection",
vascular:"related to blood vessels",
veer:"to change direction suddenly",
veil:"a covering for the face",
velocityvector:"speed with direction",
venom:"poison produced by animals",
vent:"an opening for air",
verbal:"related to spoken words",
verge:"the edge of something",
versus:"in comparison with",
vibrate:"to shake rapidly",
victimize:"to treat someone unfairly",
vigor:"physical strength and energy",
villain:"an evil character in a story",
vindicate:"to clear from blame",
violin:"a musical instrument with strings",
vitality:"energy and life",
vividness:"the quality of being vivid",
voluminous:"very large in amount",
xray:"a type of radiation used to see inside the body",
xenon:"a chemical element used in lamps",
xylophone:"a musical instrument with wooden bars",
xenophobia:"fear or dislike of foreigners",
xylem:"plant tissue that carries water",
xaxis:"the horizontal axis in a graph",
xenial:"friendly to guests",
xenolith:"a rock fragment inside another rock",
xerox:"a copy made by a machine",
xerography:"a printing process used in photocopiers",
xerophyte:"a plant adapted to dry environments",
xenogenesis:"the production of offspring different from parents",
xiphias:"a type of swordfish",
xiphoid:"a small bone at the bottom of the breastbone",
xenodochial:"friendly to strangers",
xanthic:"yellow in color",
xanthin:"a chemical compound found in plants",
xanthophyll:"a yellow pigment in plants",
xanthoma:"a yellowish skin growth",
xanthous:"yellowish colored",
xenarch:"relating to foreign rule",
xenic:"related to a foreign environment",
xenium:"a gift given to a guest",
xenograft:"tissue transplanted from another species",
xenoliths:"rock fragments enclosed in another rock",
xenology:"study of foreign cultures",
xenomania:"obsession with foreign things",
xenonlamp:"a bright lamp using xenon gas",
xenophobiafear:"fear of strangers",
xenotropic:"affecting foreign species",
xeric:"very dry",
xeriscape:"landscaping requiring little water",
xeroderma:"dry skin condition",
xerographycopy:"copy made using xerography",
xerophilous:"adapted to dry conditions",
xerophthalmia:"dryness of the eye",
xiphodon:"an extinct animal",
xiphosura:"group of horseshoe crabs",
xiphosuran:"related to horseshoe crabs",
xiphoidprocess:"small bone part of sternum",
xiphophyllous:"having sword-shaped leaves",
xmas:"short form of Christmas",
xenagogue:"a guide for strangers",
xenialhost:"a welcoming host",
xeniality:"hospitality to guests",
xenogenesisidea:"origin from outside sources",
xenolithrock:"rock fragment in lava",
xenonflash:"bright flash using xenon gas",
xenophobe:"a person who fears foreigners",
xenophilic:"attracted to foreign things",
xenophobiaattitude:"fear of outsiders",
xenotransplant:"organ transplant between species",
xerarch:"dry ecological succession",
xericplant:"plant living in dry areas",
xerophagy:"eating dry food",
xerophyteplant:"plant adapted to deserts",
xeroradiography:"a special xray process",
xerosis:"dryness of skin",
xiphoidbone:"lower part of breastbone",
xiphosword:"a sword-shaped object",
xiphosurananimal:"marine animal like horseshoe crab",
xmasday:"Christmas day celebration",
xraybeam:"beam of x-ray radiation",
xrayimage:"image created by x-rays",
xraymachine:"device used for x-ray imaging",
xrayphotograph:"photograph made using x-rays",
xraytube:"tube that produces x-rays",
xrayvision:"ability to see through objects",
xrayworker:"person operating x-ray machine",
xraytest:"test using x-ray imaging",
xraytechnology:"technology using x-rays",
xraydiagnosis:"medical diagnosis with x-rays",
xrayanalysis:"analysis using x-ray radiation",
xrayinspection:"inspection with x-rays",
xrayscanner:"machine that scans with x-rays",
xraytherapy:"treatment using x-rays",
xrayunit:"unit producing x-rays",
xraywavelength:"wavelength of x-rays",
xrayradiation:"high energy electromagnetic radiation",
xraydetector:"device detecting x-rays",
xrayexposure:"contact with x-ray radiation",
xrayplate:"plate used in imaging",
xrayroom:"room where x-rays are taken",
xraylab:"laboratory using x-rays",
xrayclinic:"clinic providing x-ray services",
xrayfilm:"film used in x-ray imaging",
xraydata:"data collected from x-rays",
xrayfield:"area exposed to x-rays",
xrayenergy:"energy carried by x-rays",
xraylight:"high energy light waves",
xraymeasurement:"measurement using x-rays",
xrayrecord:"record of x-ray results",
xrayreading:"interpretation of x-rays",
xrayreport:"report from x-ray analysis",
xrayresult:"result obtained from x-ray",
xraystudy:"study using x-ray imaging",
xraytech:"person who operates x-ray machine",
xrayview:"visualization through x-rays",
xrayzone:"area scanned by x-rays",
yard:"an area of land next to a house",
yarn:"thread used for knitting",
yawn:"to open the mouth wide when tired",
year:"a period of twelve months",
yell:"to shout loudly",
yellow:"a bright color like the sun",
yes:"a word showing agreement",
yesterday:"the day before today",
yet:"until now or still",
yield:"to produce or give way",
young:"not old",
youth:"the period of being young",
yummy:"very tasty",
yoke:"a wooden bar joining animals",
yolk:"the yellow part of an egg",
yoga:"a practice for body and mind",
yogurt:"a dairy food made from milk",
yonder:"at some distance",
yardstick:"a tool for measuring length",
yearbook:"a book published yearly",
yearly:"happening every year",
yearning:"a strong desire",
yeast:"a substance used in baking bread",
yellowish:"slightly yellow",
yellowing:"becoming yellow",
yellowstone:"a famous national park",
yelp:"a short sharp cry",
yen:"a strong desire",
yesman:"a person who agrees with everything",
yesterdaynight:"the night before today",
yielding:"giving way easily",
youngster:"a child or young person",
youthful:"having the qualities of youth",
yuppie:"a young professional person",
yodel:"to sing with rapid pitch changes",
yawner:"something boring",
yawning:"the act of yawning",
yacht:"a large boat for pleasure",
yachtsman:"a person who sails yachts",
yardage:"the number of yards",
yardman:"a worker in a yard",
yardwork:"work done in a garden",
yearend:"the end of a year",
yearlong:"lasting for a year",
yearround:"through the entire year",
yearstart:"the beginning of a year",
yearplan:"a plan for the year",
yeargain:"increase over a year",
yearloss:"decrease over a year",
yearstudy:"study lasting a year",
yearrecord:"record for the year",
yeartrend:"pattern over years",
yearvalue:"value in a year",
yeoman:"a farmer or worker",
yeomanry:"a class of farmers",
yesternight:"last night",
yieldcrop:"production from crops",
yieldrate:"rate of production",
yieldstrength:"strength before breaking",
youngadult:"a person in early adulthood",
youngage:"a small age",
youngbird:"a baby bird",
youngchild:"a small child",
younggeneration:"new generation",
youngmind:"a child's mind",
youngplant:"a small plant",
youngtree:"a small growing tree",
youngworker:"a new worker",
youthclub:"a club for young people",
youthcamp:"a camp for youth",
youthcenter:"a place for youth activities",
youthculture:"culture of young people",
youthgroup:"a group of young people",
youthleader:"a person guiding youth",
youthmovement:"a youth social movement",
youthprogram:"a program for youth",
youthservice:"services for young people",
youthsport:"sports for young people",
youthteam:"a sports team of youth",
youthtraining:"training for youth",
youthvoice:"opinions of young people",
youthwork:"work focused on youth",
youthzone:"area for youth activities",
younghope:"hope of the young",
youngtalent:"talent of a young person",
youngstudent:"a student of small age",
youngartist:"a beginner artist",
youngplayer:"a new sports player",
youngdriver:"a new driver",
youngleader:"a young leader",
youngwriter:"a new writer",
youngthinker:"a young person who thinks deeply",
youngbuilder:"a beginner builder",
youngcreator:"a young creator",
younginnovator:"a young person with new ideas",
youngscientist:"a young science learner",
youngteacher:"a new teacher",
younghero:"a brave young person",
youngdreamer:"a young person with dreams",
youngvision:"a future vision from youth",
zebra:"a wild animal with black and white stripes",
zero:"the number representing nothing",
zone:"an area or region",
zoo:"a place where animals are kept for public viewing",
zoom:"to move very quickly or enlarge an image",
zest:"great enthusiasm or energy",
zigzag:"a line with sharp turns",
zip:"to close something with a zipper",
zinc:"a chemical element used in metals",
zodiac:"a belt of stars used in astrology",
zombie:"a fictional undead person",
zoology:"the study of animals",
zoologist:"a scientist who studies animals",
zany:"funny in a silly way",
zap:"to strike suddenly with force",
zeal:"great passion for something",
zealous:"very enthusiastic",
zenith:"the highest point",
zephyr:"a gentle breeze",
zeppelin:"a large airship",
zestful:"full of energy",
zesty:"having strong flavor",
zig:"a sharp turn in a zigzag",
zag:"another sharp turn in a zigzag",
zigzagging:"moving with many sharp turns",
zillion:"a very large number",
zincplate:"a metal plate coated with zinc",
zincoxide:"a white powder made from zinc",
zipper:"a device used to fasten clothes",
zipline:"a cable for sliding down",
ziplock:"a type of sealing plastic bag",
zippy:"lively and energetic",
zircon:"a mineral used as gemstone",
zirconium:"a chemical element",
zither:"a musical instrument with strings",
zodiacal:"related to the zodiac",
zonal:"related to zones",
zoneout:"to stop paying attention",
zookeeper:"a person who cares for animals in a zoo",
zoological:"related to animals",
zoologicalpark:"another word for zoo",
zooplankton:"tiny animals floating in water",
zootopia:"an imaginary animal city",
zorbing:"a sport of rolling inside a ball",
zucchini:"a green vegetable",
zulu:"a language and African ethnic group",
zanyness:"the state of being silly",
zealot:"a person extremely devoted to something",
zealousness:"strong enthusiasm",
zebrafish:"a small striped fish used in research",
zebrastone:"a patterned rock",
zenlike:"calm and peaceful",
zenmode:"a calm focused state",
zenpractice:"meditation practice",
zephyrwind:"a soft wind",
zeppelinship:"a type of airship",
zerodegree:"temperature of zero",
zerogravity:"condition of weightlessness",
zeropoint:"exact point of zero",
zerosum:"situation where one gain equals another loss",
zestiness:"quality of strong flavor",
zigzagline:"a line with repeated sharp angles",
zigzagpattern:"a repeated zigzag design",
zigzagroad:"a road with many turns",
zincalloy:"a mixture of zinc with metals",
zincbattery:"a battery using zinc",
zincmine:"a place where zinc is extracted",
zincsheet:"a thin sheet of zinc",
zincsurface:"surface coated with zinc",
zinger:"a striking remark",
zipfastener:"another word for zipper",
zipdrive:"a type of storage device",
zipcode:"a postal code",
zipfile:"a compressed computer file",
zippycar:"a fast moving car",
zirconstone:"a gemstone made of zircon",
zirconring:"a ring with zircon stone",
zirconcrystal:"crystal form of zircon",
zitherplayer:"a person who plays zither",
zodiacsign:"astrological sign",
zodiacwheel:"circular zodiac chart",
zonalmap:"a map showing zones",
zoneborder:"edge of a zone",
zonecontrol:"control over an area",
zoneentry:"entry into an area",
zonefield:"a field divided into zones",
zoneguard:"guard of a zone",
zonelevel:"level of zone division",
zonepolicy:"rules for an area",
zonepower:"authority in a zone",
zonewatch:"monitoring an area",
zookeeperstaff:"workers in a zoo",
zoologylab:"animal research laboratory",
zoomanimation:"animation effect of zooming",
zoomcamera:"camera with zoom lens",
zoomfeature:"zoom function in devices",
zoommeeting:"online meeting using zoom",
zoomspeed:"speed of zooming",
zoomview:"enlarged view"
};
const wordContainer = document.getElementById("wordContainer");
const alphabetDiv = document.getElementById("alphabetButtons");
const searchInput = document.getElementById("searchBar");
const totalWords = Object.keys(dictionary).length;
document.getElementById("wordCount").textContent = totalWords;

function displayWords(wordsArray) {
    wordContainer.innerHTML = "";

    if (wordsArray.length === 0) {
        wordContainer.innerHTML = "<p>No words found.</p>";
        return;
    }

    wordsArray.forEach(word => {
        let card = document.createElement("div");
        card.className = "word-card";
        card.innerHTML = `<h3>${word}</h3><p>${dictionary[word]}</p>`;
        wordContainer.appendChild(card);
    });
}

function searchWord() {
    let value = searchInput.value.toLowerCase();
    let filtered = Object.keys(dictionary)
        .filter(word => word.toLowerCase().includes(value))
        .sort();
    displayWords(filtered);
}

function filterByLetter(letter) {
    searchInput.value = "";
    let filtered = Object.keys(dictionary)
        .filter(word => word.startsWith(letter))
        .sort();
    displayWords(filtered);
}

searchInput.addEventListener("input", searchWord);

for(let i = 65; i <= 90; i++) {
    let letter = String.fromCharCode(i);
    let btn = document.createElement("button");
    btn.innerText = letter;
    btn.onclick = () => filterByLetter(letter);
    alphabetDiv.appendChild(btn);
}

displayWords(Object.keys(dictionary).sort());